name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PATH="/root/.nvm/versions/node/v20.12.2/bin/"
            cd /var/apps/woundcare-backend
            git pull
            npm install
            npm run build
            pm2 restart woundcare-backend && kill $!
